name: Wine Fedora Linux CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:

      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          dnf -y -q upgrade --refresh
          cd wine-tkg-git
          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          sed -i 's/_configure_userargs64=""/_configure_userargs64="--with-pulse --with-gstreamer --without-alsa --without-coreaudio --without-oss --without-ffmpeg --without-sane --without-pcsclite --without-piper --without-vosk --without-netapi --without-capi --without-osmesa --disable-powershell --disable-winemenubuilder --disable-win16"/' wine-tkg-profiles/advanced-customization.cfg
          sed -i 's/_configure_userargs32=""/_configure_userargs32="--with-pulse --with-gstreamer --without-alsa --without-coreaudio --without-oss --without-ffmpeg --without-sane --without-pcsclite --without-piper --without-vosk --without-netapi --without-capi --without-osmesa --disable-powershell --disable-winemenubuilder --disable-win16"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
